config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :autoarts

  get 'pages/home'
  get 'myautoarts' => "autoarts#myautoarts"
  get 'userarts' => "autoarts#userarts"

  get 'tags/:tag', to: 'autoarts#index' , as: :tag
  
  root "pages#home"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/autoart.rb
class Autoart < ActiveRecord::Base

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  acts_as_taggable_on :tags

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


    has_many :autoarts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :current_password)
    end
 end


 
end

app/controllers/autoarts_controller.rb
class AutoartsController < ApplicationController
  before_action :set_autoart, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:myautoarts, :new, :create, :update, :edit, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def myautoarts
    @autoarts = Autoart.where(user: current_user).order("created_at DESC")
  end

  # GET /autoarts
  # GET /autoarts.json
  def index
    if params[:tag]
      @autoarts = Autoart.tagged_with(params[:tag])
    else  
      @autoarts = Autoart.all.order("created_at DESC")
    end
  end

  # GET /autoarts/1
  # GET /autoarts/1.json
  def show
  end

  # GET /autoarts/new
  def new
    @autoart = Autoart.new
  end

  # GET /autoarts/1/edit
  def edit
  end

  # POST /autoarts
  # POST /autoarts.json
  def create
    @autoart = Autoart.new(autoart_params)
    @autoart.user_id = current_user.id

    respond_to do |format|
      if @autoart.save
        format.html { redirect_to @autoart, notice: 'Autoart was successfully created.' }
        format.json { render :show, status: :created, location: @autoart }
      else
        format.html { render :new }
        format.json { render json: @autoart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autoarts/1
  # PATCH/PUT /autoarts/1.json
  def update
    respond_to do |format|
    @autoart.user_id = current_user.id
      if @autoart.update(autoart_params)
        format.html { redirect_to @autoart, notice: 'Autoart was successfully updated.' }
        format.json { render :show, status: :ok, location: @autoart }
      else
        format.html { render :edit }
        format.json { render json: @autoart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autoarts/1
  # DELETE /autoarts/1.json
  def destroy
    @autoart.destroy
    respond_to do |format|
      format.html { redirect_to autoarts_url, notice: 'Autoart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_autoart
      @autoart = Autoart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autoart_params
      params.require(:autoart).permit(:title, :description, :image, :tag_list)
    end

    def correct_user
      @autoart = current_user.autoarts.find_by(id: params[:id])
      redirect_to autoart_path, notice: "You have no autorization to this art" if @autoart.nil?
    end

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autoarts_helper.rb
module AutoartsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/autoarts/_form.html.erb
<%= form_for(@autoart, :html => { :multipart => true }) do |f| %>
  <% if @autoart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@autoart.errors.count, "error") %> prohibited this autoart from being saved:</h2>

      <ul>
      <% @autoart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"%>
  </div>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br>
    <%= f.text_field :tag_list %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autoarts/edit.html.erb
<h1>Editing autoart</h1>

<%= render 'form' %>

<%= link_to 'Show', @autoart %> |
<%= link_to 'Back', autoarts_path %>

app/views/autoarts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Autoart', new_autoart_path, class: "btn btn-success"%>
<% end %>
<br>
<br>
<div id="autoarts" class="transitions-enabled">
  <% @autoarts.each do |autoart| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(autoart.image.url), autoart %>
          <div class="panel-body">
            <h3><%= autoart.title %></h3>
            <% if current_user && autoart.user == current_user %>
              <%= link_to edit_autoart_path(autoart) do %>
                <span class="glyphicon glyphicon-edit"></span>
                  Edit
              <% end %>
              |<%= link_to autoart, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
                  Delete
                <% end %>
            <% end %>
          </div>
    </div>      
  <% end %>
</div>
<br>

app/views/autoarts/myautoarts.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Autoart', new_autoart_path, class: "btn btn-success" %>
<% end %>
<br>
<br>
<div id="autoarts" class="transitions-enabled">
  <% @autoarts.each do |autoart| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(autoart.image.url), autoart %>
          <div class="panel-body">
            <h3><%= autoart.title %></h3>
            <% if current_user && autoart.user == current_user %>
              <%= link_to edit_autoart_path(autoart) do %>
                <span class="glyphicon glyphicon-edit"></span>
                  Edit
              <% end %>
              |<%= link_to autoart, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
                  Delete
                <% end %>
            <% end %>
          </div>
    </div>      
  <% end %>
</div>
<br>

app/views/autoarts/new.html.erb
<h1>New autoart</h1>

<%= render 'form' %>

<%= link_to 'Back', autoarts_path %>

app/views/autoarts/show.html.erb
<div class="row">
	<div class="panel-heading center">
	<div class ="col-md-offset-2 col-md-8 ">
		<div class="thumbnail">
			<%= image_tag @autoart.image.url %>	
			 <div class="panel-body">
			 	<p><strong><%= @autoart.title %></strong></p>
			 	<p><strong><%= @autoart.description %></strong></p>
			 	<p><strong><%= "Added by : #{@autoart.user.username}" %></strong></p>
			 	<p><strong>Tags:</strong> <%= raw @autoart.tag_list.map { |t| link_to t, tag_path(t) }.join(',') %></p>
			    <%= link_to edit_autoart_path(@autoart) do%> 
                	<span class="glyphicon glyphicon-edit"></span>
                  Edit
				<% end %>
			 </div>
		</div>
	</div>
	</div>
</div>


<%= link_to 'Back', autoarts_path %>

app/views/autoarts/userarts.html.erb
<div id="autoarts" class="transitions-enabled">
  <% @autoarts.each do |autoart| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(autoart.image.url), autoart %>
          <div class="panel-body">
            <h3><%= autoart.title %></h3>

          </div>
    </div>      
  <% end %>
</div>
<br>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Kokudo246</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="">Store</a></li>
        <li><%= link_to "AutoArts", autoarts_path %></li>
        <li><a href="">Video</a></li>
        <li><a href="">Discussion</a></li>
        <li><a href="">Workshop</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Autoarts", myautoarts_path %></li>
              <li>
                <%= link_to new_autoart_path do %>
                  <span class="glyphicon glyphicon-plus"></span> New Pin
                <% end %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kokudo246</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


	<%= yield %>
</div>


</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>add picture here</h1>
	  <p><a class="btn btn-primary btn-lg" role="button">Log in</a></p>
	  <p><a class="btn btn-primary btn-lg" role="button">sign up</a></p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="Rails" src="/assets/dis.jpeg" />
      <div class="caption">
        <h3>Kokudo246 Store</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="Rails" src="/assets/dis.jpeg" />
      <div class="caption">
        <h3>AutoArts</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="Rails" src="/assets/dis.jpeg" />
      <div class="caption">
        <h3>Video</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="Rails" src="/assets/dis.jpeg" />
      <div class="caption">
        <h3>Discussion</h3>
        <p>bla bla blaasdfoh asdohf asdf@ohsdf asdofguha sdfasodfgasodfb asdfougasdf asodfoasduf asodfboasgduf asodfoasdfoashdfoasdghfo osaudgf oashgdfo ashdf ohgasdfog asdfoosa@udfg ska;dbfoasgf ipasdgf :oasdgf@oapsgf;as</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
    
    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img alt="Rails" src="/assets/dis.jpeg" />
      <div class="caption">
        <h3>Workshop</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>

</div>